version: "3"

services:
  nonebot:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env.prod
    environment:
      ENVIRONMENT: prod
      SQLALCHEMY_DATABASE_URL: sqlite+aiosqlite:////data/data.db
      HOST: 0.0.0.0
      PORT: 8080
    volumes:
      - /data:./data
    restart: always